name: DarkAuction
version: ${project.version}
main: me.deadlight.darkauction.DarkAuction
api-version: 1.13
authors: [Dead_Light]
description: Hypixel Dark Auction remade
depend: [Citizens, Vault]
softdepend: [PlaceholderAPI]
commands:
  da:
    description: the main command which is used for server admin